theme: jekyll-theme-slate
title: 1,2,3, Durable ! 
description: Le projet 1,2,3 Durable est issus du conseil de quartier Croix Rousse Centre est vise à accélérer la mise en place du développement durable dans le 4eme arrondissement de Lyon
